name: Vyne CI

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential g++

      - name: Compile Vyne
        run: |
          g++ -std=c++17 main.cpp \
              vyne/compiler/lexer/lexer.cpp \
              vyne/compiler/parser/parser.cpp \
              vyne/compiler/ast/ast.cpp \
              vyne/compiler/ast/value.cpp \
              vyne/modules/vcore/vcore.cpp \
              vyne/modules/vglib/vglib.cpp \
              vyne/modules/vmem/vmem.cpp \
              cli/repl.cpp \
              cli/file_handler.cpp \
              -o vyne_run -Wall -Wextra

      - name: Run Tests
        run: |
          for testfile in tests/*.vy; do
            if [ -f "$testfile" ]; then
              echo "---------------------------------------"
              echo "Running $testfile..."
              ./vyne_run "$testfile"
            fi
          done
